name: Discord Issue Webhook

on:
  issues:
    types: [opened, reopened]

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send issue embed to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "New Issue: ${{ github.event.issue.title }}"
          embed-url: "${{ github.event.issue.html_url }}"
          embed-description: "${{ github.event.issue.body }}"
          embed-color: 5814783
          embed-author-name: "${{ github.event.issue.user.login }}"
          embed-author-icon-url: "${{ github.event.issue.user.avatar_url }}"
          embed-footer-text: "Issue #${{ github.event.issue.number }}"
          embed-timestamp: "${{ github.event.issue.created_at }}"
